const { readFileSync, writeFileSync } = require("fs");
const { join } = require("path");

const axios = require("axios");
const { parseStringPromise } = require("xml2js");

const URL = "https://darekkay.com/atom.xml";
const README = join(__dirname, "README.md");
const AUTOGENERATED_MARKER = "<!-- autogenerated -->";

const sync = async () => {
  const response = await axios.get(URL);
  const { feed } = await parseStringPromise(response.data);

  const latestPosts = feed.entry.slice(0, 3).map(entry => ({
    title: entry.title[0],
    url: entry.link[0]["$"]["href"]
  }));

  const readmeContent = readFileSync(README, "utf-8");

  let updatedReadmeContent = readmeContent.substring(0, readmeContent.indexOf(AUTOGENERATED_MARKER) + AUTOGENERATED_MARKER.length);
  updatedReadmeContent += latestPosts.reduce((acc, post) => `${acc}- [${post.title}](${post.url})\n`, "\n\n");

  writeFileSync(README, updatedReadmeContent);
};

sync().catch(error => console.error(error));
