name: Keep Alive
on:
  schedule:
    - cron:  '0 0 22 * *'

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Commit a dummy change
        run: |-
          git config --global user.email "keep-alive-bot@example.com"
          git config --global user.name "🔃 Keep Alive Bot"
          git commit --allow-empty -m "Keep workflow alive"
          git push
